[tasks."verify"]
script = '''
cd scripts
bun src/verify.ts
'''

[tasks."build:circuit"]
script = '''
cd circuit
bun i
circom main.circom --r1cs --wasm
'''

[tasks."dev:ui"]
script = '''
cd frontend
bun run dev
'''

[tasks."dev:prover-server"]
script = '''
cd prover
cargo run --bin server
'''

[tasks."test:build-proof"]
script = '''
cd prover
cargo run --example build_proof
'''