[tasks."verify"]
script = '''
cd scripts
bun src/verify.ts
'''

[tasks."build:circuit"]
script = '''
cd circuits
circom multiplier.circom --r1cs --wasm --sym -o build
'''

[tasks."dev:ui"]
script = '''
cd frontend
bun run dev
'''

[tasks."dev:prover-server"]
script = '''
cd prover
cargo run --bin server
'''

[tasks."test:build-proof"]
script = '''
cd prover
cargo run --example build_proof
'''

[tasks."deploy:sui"]
script = '''
cd contracts
sui client publish --gas-budget 123456789 --skip-dependency-verification
'''